# Generated by Django 2.1.3 on 2018-12-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('hashtags', models.CharField(max_length=300)),
            ],
        ),
    ]
