# Generated by Django 2.1.3 on 2018-12-24 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='username_hash',
            field=models.CharField(default='7d97481b1fe66f4b51db90da7e794d9f', max_length=32),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 24)),
        ),
    ]
