# Generated by Django 2.1.3 on 2018-12-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20181224_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
