# Generated by Django 2.1.3 on 2018-12-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20181226_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='usernama',
            new_name='username',
        ),
    ]
