# Generated by Django 2.1.3 on 2018-12-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20181226_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
