# Generated by Django 2.1.4 on 2018-12-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20181227_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('browser', models.CharField(max_length=100)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
    ]
