# Generated by Django 2.1.4 on 2018-12-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_blockedip_requestdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetail',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
