# Generated by Django 2.1.4 on 2018-12-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_requestdetail_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_ip', models.CharField(max_length=15)),
                ('captcha_text', models.CharField(max_length=100)),
            ],
        ),
    ]
