# Generated by Django 2.1.4 on 2018-12-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_captcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=100)),
                ('failed_attempts', models.IntegerField()),
            ],
        ),
    ]
